model_config:
  model_name: "qwen3.5"
  model_path: "/data/models/Qwen3.5-122B-A10B"
  exe_mode: "ge_graph"        # ["eager", "ge_graph", "npugraph_ex"]
  enable_profiler: False  # [False, True]
  with_ckpt: True
  enable_cache_compile: False
  force_eplb: False
  custom_params:
      # enable_mm_all_reduce_base: Whether to fuse TP matmul and all_reduce with npu_mm_all_reduce_base (default: False)
      # enable_gdn_solve_triangular: Whether to use solve_triangular in Qwen3.5 GatedDeltaNet chunk rule (default: False)
      enable_mm_all_reduce_base: False # Only support 950.
      enable_gdn_solve_triangular: False

data_config:
  dataset: "default"  # ["default", "LongBench"]
  input_truncated_len: 2048

parallel_config:
  world_size: 8
  attn_tp_size: 8
  moe_tp_size: 8
  embed_tp_size: 8
  lmhead_tp_size: 8
  shared_tp_size: 1
  # Derivations (not configurable):
  # attn_dp_size = world_size // attn_tp_size = 1
  # moe_ep_size = world_size // moe_tp_size = 1

scheduler_config:
  max_new_tokens: 128
  batch_size: 4
