model_config:
  model_name: "longcat-flash-lite"
  model_path: "/data/models/LongCat-Flash-Lite"
  exe_mode: "eager"
  with_ckpt: false

parallel_config:
  world_size: 1
  attn_tp_size: 1
  moe_tp_size: 1
  embed_tp_size: 1
  lmhead_tp_size: 1

scheduler_config:
  input_max_len: 1024
  max_new_tokens: 32
  batch_size: 1
