model_config:
  model_name: "longcat_flash_lite"
  model_path: "/data/models/LongCat-Flash-Lite"
  exe_mode: "ge_graph"
  with_ckpt: True

parallel_config:
  world_size: 8
  attn_tp_size: 8
  dense_tp_size: 8
  moe_tp_size: 8
  embed_tp_size: 8
  lmhead_tp_size: 8

scheduler_config:
  max_new_tokens: 128
  batch_size: 1

data_config:
  dataset: "default"
  input_truncated_len: 256        # default_prompt.json is ~256 tokens
