model_name: "deepseek_r1"  # keep it for backward compatibility.
world_size: 32  # keep it for backward compatibility.

model_config:
  model_name: "deepseek_r1"
  model_path: "/data/models/origin/DeepSeek-R1-W8A8"
  with_ckpt: True                   # [False, True]
  exe_mode: "ge_graph"              # ["eager", "npugraph_ex", "ge_graph"]
  enable_profiler: False            # [False, True]
  force_eplb: False                 # [False, True]
  enable_cache_compile: False       # [False, True]
  custom_params:
    enable_weight_nz: True            # [False, True]
    enable_mla_prolog: False          # [False, True]
    enable_multi_streams: True        # [False, True]
    enable_superkernel: False         # [False, True]
    moe_chunk_max_len: 65536
    micro_batch_mode: 1               # [0, 1]

data_config:
  dataset: "LongBench"  # ["default", "LongBench", "InfiniteBench"]
  input_truncated_len: 4096

parallel_config:
  world_size: 32
  attn_tp_size: 1
  dense_tp_size: 1
  moe_tp_size: 1
  embed_tp_size: 32
  lmhead_tp_size: 32

scheduler_config:
  block_size: 128
  max_new_tokens: 10
  batch_size: 64
