model_name: "gemma-4"
world_size: 1  # keep it for backward compatibility.

model_config:
  model_name: "gemma-4"
  model_path: "/data/models/gemma-4-26B-A4B"
  exe_mode: "eager"
  with_ckpt: True
  enable_profiler: False
  custom_params:
    enable_online_split_weight: True

data_config:
  dataset: "default"
  input_truncated_len: 256

parallel_config:
  world_size: 1
  attn_tp_size: 1
  moe_tp_size: 1
  lmhead_tp_size: 1

scheduler_config:
  max_new_tokens: 32
  batch_size: 1
