model_name: "qwen3-moe"
world_size: 128

model_config:
  model_name: "qwen3-moe"
  model_path: "/data/models/Qwen3-235B-A22B"
  exe_mode: "ge_graph"        # ["ge_graph", "eager", "npugraph_ex"]
  enable_profiler: False  # [False, True]
  with_ckpt: True # [False, True]
  enable_cache_compile: False
  perfect_eplb: False # [False, True]

data_config:
  dataset: "LongBench"  # ["default", "LongBench"]
  input_truncated_len: 4096

parallel_config:
  world_size: 128
  attn_tp_size: 1
  moe_tp_size: 1
  embed_tp_size: 1
  lmhead_tp_size: 1

scheduler_config:
  max_new_tokens: 256
  batch_size: 128
