model_name: "deepseek_v4"
model_path: "/data/models/deepseek_v4"
exe_mode: "npugraph_ex"          # ["eager", "npugraph_ex"], mode of decode
world_size: 16

model_config:
  next_n: 3
  pa_block_size: 128
  with_ckpt: True                   # [False, True]
  enable_multi_streams: True        # [False, True]
  enable_profiler: False            # [False, True]
  perfect_eplb: False               # [False, True]
  enable_cache_compile: False       # [False, True]
  enable_online_split_weight: True  # [False, True]
  prefill_mini_batch_size: 0
  platform_version: "950"
  enable_static_kernel: False       # [False, True]

data_config:
  dataset: InfiniteBench
  input_max_len: 8192
  max_new_tokens: 256
  batch_size: 16
  temperature: 1.0

parallel_config:
  cp_size: 1
  oproj_tp_size: 1
  attn_tp_size: 1
  moe_tp_size: 1
  embed_tp_size: 1
  lmhead_tp_size: 1
