model_config:
  model_name: "hy3"
  model_path: "/data/models/Hy3-BF16"
  platform_version: "A3"
  exe_mode: "npugraph_ex"           # ["ge_graph", "eager", "npugraph_ex"]
  with_ckpt: True                   # [False, True]
  enable_profiler: False            # [False, True]
  enable_cache_compile: False       # [False, True]
  custom_params:
    enable_online_split_weight: True    # [False, True]
    enable_multi_streams: False         # [False, True]
    enable_sp: False                    # [False, True]; A3 dense_tp>1 须 False

data_config:
  dataset: "default"                # ["default", "LongBench"]
  input_truncated_len: 400

parallel_config:
  world_size: 16
  attn_tp_size: 4
  dense_tp_size: 4
  moe_tp_size: 1
  embed_tp_size: 4
  lmhead_tp_size: 4

scheduler_config:
  max_new_tokens: 112
  batch_size: 4
  mem_fraction_static: 0.45
