model_args:
  config: "configs/sana_video_config/Sana_2000M_480px_AdamW_fsdp.yaml"
  model_path: "./SANA-Video_2B_480p/checkpoints/SANA_Video_2B_480p.pth"
  vae.vae_pretrained: "./SANA-Video_2B_480p/vae/Wan2.1_VAE.pth"
  text_encoder.text_encoder_name: "./gemma-2-2b-it"
  txt_file: "asset/samples/video_prompts_samples.txt"
  work_dir: "output/sana_t2v_video_results"
  cfg_scale: 6
  motion_score: 30
  flow_shift: 8
  model.fp32_attention: "False"      # [False, True]

model_name: "sana-video"
world_size: 1
master_port: 29600
entry_script: "inference_video_scripts/inference_sana_video.py"
launcher: "accelerate"

launcher_args:
  mixed_precision: "bf16"            # [no, fp16, bf16, fp8]

env_vars:
  DISABLE_XFORMERS: "1"              # [0, 1]
  HF_HUB_OFFLINE: "1"                # [0, 1]
  TRANSFORMERS_OFFLINE: "1"          # [0, 1]
  HF_DATASETS_OFFLINE: "1"           # [0, 1]
