model_config:
  model_name: "deepseek_v4"
  model_path: "/data/models/deepseek_v4_int8_w8a8"
  platform_version: "A3"
  with_ckpt: True
  exe_mode: "eager"
  enable_static_kernel: False
  enable_dynamic_graph: False
  enable_profiler: False
  force_eplb: False
  enable_cache_compile: False
  custom_params:
    enable_multi_streams: False
    enable_pypto: False
    enable_limit_core: False
    moe_chunk_max_len: 65536

data_config:
  temperature: 1.0

parallel_config:
  world_size: 16
  cp_size: 1
  attn_tp_size: 1
  dense_tp_size: 1
  moe_tp_size: 1
  embed_tp_size: 1
  lmhead_tp_size: 4
  o_proj_tp_size: 1

scheduler_config:
  block_size: 128
  max_new_tokens: 1
  max_prefill_tokens: 8192
  batch_size: 16
  mem_fraction_static: 0.80
