model_config:
  model_name: "glm_5"
  model_path: "/data/models/GLM-5-W8A8"
  exe_mode: "npugraph_ex"       # ["eager", "npugraph_ex", "ge_graph"], mode of decode
  platform_version: "A3"        # ["A3", "950"]
  with_ckpt: True               # [False, True]
  next_n: 3
  force_eplb: False             # [False, True]
  enable_weight_nz: True
  enable_profiler: False        # [False, True]
  enable_cache_compile: False   # [False, True]
  enable_dynamic_graph: False   # [False, True]
  custom_params:
    enable_multi_streams: True  # [False, True]

data_config:
  input_truncated_len: 8192

parallel_config:
  world_size: 32
  cp_size: 1
  o_proj_tp_size: 16
  attn_tp_size: 1
  dense_tp_size: 8
  moe_tp_size: 1
  embed_tp_size: 32
  lmhead_tp_size: 32

scheduler_config:
  block_size: 128
  max_prefill_tokens: 8192
  max_new_tokens: 4096
  batch_size: 32
  mem_fraction_static: 0.92
