model_args:
  ckpt_dir: "/path/to/Wan2.2-I2V-14B"
  image: "examples/i2v_input.JPG"
  prompt: "Summer beach vacation style, a white cat wearing sunglasses sits on a surfboard. The fluffy-furred feline gazes directly at the camera with a relaxed expression. Blurred beach scenery forms the background featuring crystal-clear waters, distant green hills, and a blue sky dotted with white clouds. The cat assumes a naturally relaxed posture, as if savoring the sea breeze and warm sunlight. A close-up shot highlights the feline's intricate details and the refreshing atmosphere of the seaside."
  task: "i2v-A14B"
  size: "1280*720"
  frame_num: 81                      # 4n+1
  sample_steps: 40
  base_seed: 100
  cfg_size: 2
  ulysses_size: 4
  ring_size: 1
  dit_fsdp: true                     # [false, true]
  t5_fsdp: true                      # [false, true]
  vae_parallel: true                 # [false, true]

model_name: "wan2.2-i2v"
world_size: 8
master_port: 29600
entry_script: "generate.py"

env_vars:
  PYTORCH_NPU_ALLOC_CONF: "expandable_segments:True"
  TASK_QUEUE_ENABLE: "2"
  CPU_AFFINITY_CONF: "1"

dit_cache:
  method: "NoCache"                  # [NoCache]
  enable_separate_cfg: true          # [false, true]
