model_config:
  model_name: "deepseek_v3_2_exp"
  model_path: "/data/models/DeepSeek-V3.2-Exp-Bfloat16"
  exe_mode: "ge_graph"          # ["eager", "npugraph_ex", "ge_graph"], mode of decode
  with_ckpt: True               # [False, True]
  next_n: 1
  force_eplb: False             # [False, True]
  enable_weight_nz: True
  enable_profiler: False        # [False, True]
  enable_cache_compile: False   # [False, True]
  custom_params:
    enable_multi_streams: True  # [False, True]
    enable_offload: False

data_config:
  dataset: InfiniteBench
  input_truncated_len: 65536

parallel_config:
  world_size: 64              # world_size = 2 * chip_num in A3
  cp_size: 64                 # only active at prefill stage
  o_proj_tp_size: 8           # only support when attn_tp_size == 1
  attn_tp_size: 1
  dense_tp_size: 1
  moe_tp_size: 1
  embed_tp_size: 16
  lmhead_tp_size: 16

scheduler_config:
  block_size: 128
  max_new_tokens: 256
  batch_size: 64
  max_prefill_tokens: 65536
