if(NOT DEFINED ASCEND_HOME_PATH OR ASCEND_HOME_PATH STREQUAL "")
    if(DEFINED ENV{ASCEND_HOME_PATH} AND NOT "$ENV{ASCEND_HOME_PATH}" STREQUAL "")
        set(ASCEND_HOME_PATH "$ENV{ASCEND_HOME_PATH}")
    else()
        set(ASCEND_HOME_PATH "$ENV{HOME}/ascend/cann")
    endif()
endif()
if(NOT DEFINED SHMEM_ROOT OR SHMEM_ROOT STREQUAL "")
    set(SHMEM_ROOT "$ENV{SHMEM_ROOT}")
endif()
if(SHMEM_ROOT STREQUAL "" AND DEFINED ENV{SHMEM_HOME_PATH})
    set(SHMEM_ROOT "$ENV{SHMEM_HOME_PATH}/shmem")
endif()
if(SHMEM_ROOT STREQUAL "")
    set(SHMEM_ROOT "$ENV{HOME}/ascend/shmem/latest/shmem")
endif()

if(ASCEND_HOME_PATH STREQUAL "")
    message(FATAL_ERROR "ASCEND_HOME_PATH is required")
endif()
if(SHMEM_ROOT STREQUAL "")
    message(FATAL_ERROR "SHMEM_ROOT is required")
endif()
set(ASCEND_CANN_PACKAGE_PATH "${ASCEND_HOME_PATH}")

set(BISHENG "${ASCEND_HOME_PATH}/x86_64-linux/ccec_compiler/bin/bisheng")
if(NOT DEFINED SHMEM_LIBRARY_DIR OR SHMEM_LIBRARY_DIR STREQUAL "")
    set(SHMEM_LIBRARY_DIR "${SHMEM_ROOT}/lib")
endif()
if(NOT EXISTS "${BISHENG}")
    message(FATAL_ERROR "Bisheng compiler not found: ${BISHENG}")
endif()
if(NOT EXISTS "${SHMEM_ROOT}/include/shmem.h")
    message(FATAL_ERROR "SHMEM host headers not found: ${SHMEM_ROOT}/include/shmem.h")
endif()
if(NOT EXISTS "${SHMEM_LIBRARY_DIR}/libshmem.so")
    message(FATAL_ERROR "SHMEM library not found: ${SHMEM_LIBRARY_DIR}/libshmem.so")
endif()
message(STATUS "SHMEM library directory: ${SHMEM_LIBRARY_DIR}")

set(CMAKE_CXX_COMPILER "${BISHENG}" CACHE FILEPATH "Bisheng compiler" FORCE)
# CANN's ASC language modules also read this environment variable.
set(ENV{ASCEND_HOME_PATH} "${ASCEND_HOME_PATH}")
set(CMAKE_ASC_COMPILER "${BISHENG}" CACHE FILEPATH "Ascend C compiler" FORCE)
list(APPEND CMAKE_MODULE_PATH
    "${ASCEND_HOME_PATH}/compiler/tikcpp/ascendc_kernel_cmake/asc_modules"
)
set(CMAKE_ASC_STANDARD 17)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
message(STATUS "CANN installation: ${ASCEND_HOME_PATH}")
message(STATUS "SHMEM installation: ${SHMEM_ROOT}")
set(DISTRIBUTED_EMBEDDING_NPU_ARCH "dav-3510" CACHE STRING
    "NPU architecture for the distributed embedding operator")
