# coding=utf-8
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# pylint: disable=protected-access  # tests inspect queue internals (_read_metadata, _resolve_pending_reqs, ...)

from unittest.mock import Mock

from executor.online.kv_transfer import KVPoll
from executor.online.scheduler.queues import (
    DecodePreallocQueue,
    DecodeTransferQueue,
)


def test_commit_metadata_on_transfer_success():
    queue = DecodeTransferQueue(Mock())
    decode_req = Mock()
    decode_req.req.request_id = 11
    decode_req.req.bootstrap_room = 1
    decode_req.req.finish_reason = None
    decode_req.kv_receiver.poll_and_all_reduce.return_value = KVPoll.Success
    decode_req.metadata_buffer_index = 0
    queue.waiting.append(decode_req)
    queue._read_metadata = Mock(
        return_value={
            "request_id": 11,
            "output_bootstrap_room": 1,
            "output_id": 7,
            "kv_len": 3,
        }
    )
    done = queue.pop_transferred()
    assert done == [decode_req]
    assert decode_req.req.computed_len == 3


def test_commit_metadata_rejects_bootstrap_room_mismatch():
    # request_id is NOT validated: prefill and decode run independent request_id
    # counters, so the IDs for the same logical request will differ across processes.
    # bootstrap_room (UUID generated by the router) is the correct correlation key.
    queue = DecodeTransferQueue(Mock())
    decode_req = Mock()
    decode_req.req.request_id = 11
    decode_req.req.bootstrap_room = 1
    decode_req.req.finish_reason = None
    decode_req.kv_receiver.poll_and_all_reduce.return_value = KVPoll.Success
    decode_req.metadata_buffer_index = 0
    queue.waiting.append(decode_req)
    queue._read_metadata = Mock(
        return_value={
            "request_id": 99,          # different request_id — intentionally ignored
            "output_bootstrap_room": 2,  # wrong room → should error
            "output_id": 7,
            "kv_len": 3,
        }
    )
    done = queue.pop_transferred()
    assert done == []
    assert decode_req.req.finish_reason == "error"


def test_decode_uses_query_dp_ranks():
    transfer_queue = Mock()
    metadata_pool = Mock()
    metadata_pool.alloc.return_value = 0
    kv_transfer_manager = Mock()
    kv_transfer_manager.prefill_info_table = {}
    kv_transfer_manager.try_ensure_parallel_info.return_value = True
    kv_transfer_manager.query_prefill_dp_ranks.return_value = {1: 3}

    queue = DecodePreallocQueue(
        kv_transfer_manager=kv_transfer_manager,
        kv_cache_manager=Mock(),
        metadata_pool=metadata_pool,
        transfer_queue=transfer_queue,
        running_requests={},
        num_reserved_decode_tokens=64,
        max_prefill_tokens=4096,
    )
    req = Mock()
    req.bootstrap_room = 1
    req.bootstrap_addr = "127.0.0.1:18800"
    req.disagg_prefill_dp_rank = -1
    decode_req = queue._create_receiver_and_enqueue(req)
    decode_req.kv_receiver = Mock()
    queue.pending_reqs = [decode_req]
    queue._resolve_pending_reqs()
    assert decode_req.kv_receiver.init.call_args.args[0] == 3


def test_decode_keeps_pending_req_until_retry_limit():
    transfer_queue = Mock()
    kv_transfer_manager = Mock()
    kv_transfer_manager.prefill_info_table = {}
    kv_transfer_manager.try_ensure_parallel_info.return_value = False
    metadata_pool = Mock()
    queue = DecodePreallocQueue(
        kv_transfer_manager=kv_transfer_manager,
        kv_cache_manager=Mock(),
        metadata_pool=metadata_pool,
        transfer_queue=transfer_queue,
        running_requests={},
        num_reserved_decode_tokens=64,
        max_prefill_tokens=4096,
    )
    req = Mock()
    req.bootstrap_room = 5
    req.bootstrap_addr = "127.0.0.1:18800"
    decode_req = queue._create_receiver_and_enqueue(req)
    ready, remaining = queue._ensure_prefill_info({req.bootstrap_addr: [decode_req]})
    assert ready == {}
    assert remaining == [decode_req]


def test_decode_query_miss_aborts_after_retry_limit():
    transfer_queue = Mock()
    metadata_pool = Mock()
    kv_transfer_manager = Mock()
    kv_transfer_manager.prefill_info_table = {"127.0.0.1:18800": Mock(dp_size=2)}
    kv_transfer_manager.try_ensure_parallel_info.return_value = True
    kv_transfer_manager.query_prefill_dp_ranks.return_value = {}
    queue = DecodePreallocQueue(
        kv_transfer_manager=kv_transfer_manager,
        kv_cache_manager=Mock(),
        metadata_pool=metadata_pool,
        transfer_queue=transfer_queue,
        running_requests={},
        num_reserved_decode_tokens=64,
        max_prefill_tokens=4096,
    )
    req = Mock()
    req.bootstrap_room = 9
    req.bootstrap_addr = "127.0.0.1:18800"
    req.disagg_prefill_dp_rank = -1
    decode_req = queue._create_receiver_and_enqueue(req)
    decode_req.kv_receiver = Mock()
    queue.pending_reqs = [decode_req]
    queue.MAX_RETRIES = 1
    queue._resolve_pending_reqs()
    decode_req.kv_receiver.abort.assert_called_once()
