model_config:
  model_name: "hy3"
  model_path: "/data/models/Hy3-MXFP4"
  platform_version: "950"
  exe_mode: "npugraph_ex"           # ["ge_graph", "eager", "npugraph_ex"]
  with_ckpt: True                   # [False, True]
  enable_profiler: False            # [False, True]
  enable_cache_compile: False       # [False, True]
  next_n: 1
  custom_params:
    enable_online_split_weight: True    # [False, True]
    enable_multi_streams: True          # [False, True]
    enable_sp: True                     # [False, True]
    enable_fia_fp8: True                # [False, True]
    enable_qkv_fused_kscale: True       # [False, True]

data_config:
  dataset: "default"                # ["default", "LongBench"]
  input_truncated_len: 400

parallel_config:
  world_size: 4
  attn_tp_size: 4
  dense_tp_size: 1
  moe_tp_size: 1
  embed_tp_size: 4
  lmhead_tp_size: 4

scheduler_config:
  max_new_tokens: 128
  batch_size: 4
