model_args:
  model-id: "./ckpts/weight_ep8"
  prompt: "A cinematic medium shot captures a single Asian woman seated on a chair within a dimly lit room, creating an intimate and theatrical atmosphere."
  image-size: "1024x1024"            # WxH
  seed: 42
  diff-infer-steps: 50
  reproduce: true                    # [false, true]
  attn-impl: "npu"                   # [sdpa, flash_attention_2, npu]
  moe-impl: "npu_grouped_matmul"     # [eager, flashinfer, npu_grouped_matmul]
  moe-ep: true                       # [false, true]
  verbose: 0

model_name: "hunyuan-image-3.0"
world_size: 16
master_port: 10086
entry_script: "run_image_gen.py"

env_vars:
  CFG_PARALLEL: "1"                  # [0, 1]
  USE_VAE_PARALLEL: "1"              # [0, 1]
  CPU_AFFINITY_CONF: "2"
