model_args:
  model-base: "ckpts"
  prompt: "A cat walks on the grass, realistic style."
  video-size: [720, 1280]            # [H, W]
  video-length: 129                  # 4n+1
  infer-steps: 50
  seed: 42
  embedded-cfg-scale: 6.0
  flow-shift: 7.0
  flow-reverse: true                 # [false, true]
  ulysses-degree: 1
  ring-degree: 8
  use-cpu-offload: true              # [false, true]
  use-vae-parallel: true             # [false, true]

model_name: "hunyuan-video"
world_size: 8
master_port: 29600
entry_script: "sample_video.py"

dit_cache:
  method: "NoCache"                  # [NoCache]

sparse:
  method: "TopK"                     # [TopK, SVG]
  block_size_Q: 128
  block_size_K: 512
  model: "HunyuanVideo"
  params:
    TopK:
      sparse_time_step: "10-49"      # "start-end"
      sparsity_files_path: "./sparsity/720x1280x129/v3"
      CAC_threshold: 0.9
      ring_sparse_overlap: true
    SVG:
      sparse_time_step: "14-49"      # "start-end"
      sparsity: 0.8
      sample_mse_max_row: 5000
      context_length: 256
