model_name: "hy3"
world_size: 16 # keep it for backward compatibility.

model_config:
  model_name: "hy3"
  model_path: "/data/models/hy3-preview"
  exe_mode: "ge_graph"
  enable_profiler: False
  with_ckpt: True
  enable_cache_compile: True
  custom_params:
    enable_online_split_weight: True
    enable_superkernel: True
    enable_multi_streams: False

data_config:
  dataset: "default"
  input_truncated_len: 400

parallel_config:
  world_size: 16
  attn_tp_size: 4
  dense_tp_size: 4
  moe_tp_size: 1
  embed_tp_size: 4
  lmhead_tp_size: 4

scheduler_config:
  batch_size: 16
  max_new_tokens: 112
